version: '3.8'

services:
  web:
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=coollekt
      - POSTGRES_PASSWORD=coollekt
      - POSTGRES_DB=coollekt_dev

volumes:
  postgres_data: