# Generated by Django 4.0.2 on 2022-02-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coollekt', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
